import '../models/models.dart';

enum CatalogMount { floor, wall, ceiling }

class ObjectCatalogItem {
  const ObjectCatalogItem({
    required this.id,
    required this.name,
    required this.group,
    required this.type,
    required this.widthMm,
    required this.depthMm,
    required this.heightMm,
    this.elevationMm = 0,
    this.mount = CatalogMount.floor,
  });

  final String id;
  final String name;
  final String group;
  final PlanObjectType type;
  final double widthMm;
  final double depthMm;
  final double heightMm;
  final double elevationMm;
  final CatalogMount mount;

  String get mountLabel => switch (mount) {
    CatalogMount.floor => 'На пол',
    CatalogMount.wall => 'На стену',
    CatalogMount.ceiling => 'На потолок',
  };
}

class ObjectCatalog {
  static const items = <ObjectCatalogItem>[
    ObjectCatalogItem(
      id: 'sofa-3',
      name: 'Диван 3-местный',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 2200,
      depthMm: 900,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'sofa-2',
      name: 'Диван 2-местный',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 1700,
      depthMm: 900,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'armchair',
      name: 'Кресло',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 850,
      depthMm: 850,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'bed-160',
      name: 'Кровать 160×200',
      group: 'Кровати',
      type: PlanObjectType.furniture,
      widthMm: 1700,
      depthMm: 2100,
      heightMm: 950,
    ),
    ObjectCatalogItem(
      id: 'bed-180',
      name: 'Кровать 180×200',
      group: 'Кровати',
      type: PlanObjectType.furniture,
      widthMm: 1900,
      depthMm: 2100,
      heightMm: 950,
    ),
    ObjectCatalogItem(
      id: 'wardrobe-2',
      name: 'Шкаф 2 двери',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 1000,
      depthMm: 600,
      heightMm: 2200,
    ),
    ObjectCatalogItem(
      id: 'wardrobe-3',
      name: 'Шкаф 3 двери',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 1500,
      depthMm: 600,
      heightMm: 2200,
    ),
    ObjectCatalogItem(
      id: 'table-rect',
      name: 'Стол прямоугольный',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1400,
      depthMm: 800,
      heightMm: 750,
    ),
    ObjectCatalogItem(
      id: 'table-round',
      name: 'Стол круглый',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1000,
      depthMm: 1000,
      heightMm: 750,
    ),
    ObjectCatalogItem(
      id: 'chair',
      name: 'Стул',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 480,
      depthMm: 520,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'kitchen-base',
      name: 'Кухонный модуль 600',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-base-300',
      name: 'Кухонный модуль 300',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 300,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-base-400',
      name: 'Кухонный модуль 400',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 400,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-base-800',
      name: 'Кухонный модуль 800',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 800,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-sink',
      name: 'Мойка 600',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-oven',
      name: 'Духовой шкаф 600',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'kitchen-upper',
      name: 'Навесной шкаф 600',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 350,
      heightMm: 720,
      elevationMm: 1450,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'kitchen-tall',
      name: 'Пенал 600',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 2200,
    ),
    ObjectCatalogItem(
      id: 'fridge',
      name: 'Холодильник',
      group: 'Бытовая техника',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 650,
      heightMm: 1900,
    ),
    ObjectCatalogItem(
      id: 'washer',
      name: 'Стиральная машина',
      group: 'Бытовая техника',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'dishwasher',
      name: 'Посудомоечная машина',
      group: 'Бытовая техника',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'dryer',
      name: 'Сушильная машина',
      group: 'Бытовая техника',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'tv',
      name: 'Телевизор 55″',
      group: 'Видео и ТВ',
      type: PlanObjectType.furniture,
      widthMm: 1230,
      depthMm: 70,
      heightMm: 720,
      elevationMm: 900,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'toilet',
      name: 'Унитаз',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 390,
      depthMm: 700,
      heightMm: 760,
    ),
    ObjectCatalogItem(
      id: 'sink',
      name: 'Раковина',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 600,
      depthMm: 480,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'bath',
      name: 'Ванна 1700',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 1700,
      depthMm: 750,
      heightMm: 600,
    ),
    ObjectCatalogItem(
      id: 'shower',
      name: 'Душевая 900×900',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 900,
      depthMm: 900,
      heightMm: 2100,
    ),
    ObjectCatalogItem(
      id: 'bidet',
      name: 'Биде',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 380,
      depthMm: 600,
      heightMm: 420,
    ),
    ObjectCatalogItem(
      id: 'mirror',
      name: 'Зеркало',
      group: 'Сантехника',
      type: PlanObjectType.furniture,
      widthMm: 800,
      depthMm: 40,
      heightMm: 700,
      elevationMm: 1100,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'desk',
      name: 'Рабочий стол',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1200,
      depthMm: 600,
      heightMm: 750,
    ),
    ObjectCatalogItem(
      id: 'shelf',
      name: 'Стеллаж',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 800,
      depthMm: 350,
      heightMm: 2000,
    ),
    ObjectCatalogItem(
      id: 'radiator',
      name: 'Радиатор 900',
      group: 'Отопление',
      type: PlanObjectType.radiator,
      widthMm: 900,
      depthMm: 120,
      heightMm: 600,
      elevationMm: 120,
    ),
    ObjectCatalogItem(
      id: 'sofa-corner',
      name: 'Диван угловой',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 2600,
      depthMm: 1700,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'dining-table-6',
      name: 'Стол обеденный на 6 мест',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1800,
      depthMm: 900,
      heightMm: 760,
    ),
    ObjectCatalogItem(
      id: 'kitchen-island',
      name: 'Кухонный остров',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 1800,
      depthMm: 900,
      heightMm: 900,
    ),
    ObjectCatalogItem(
      id: 'vanity-800',
      name: 'Тумба с раковиной 800',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 800,
      depthMm: 500,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'shower-1200',
      name: 'Душевая 1200×900',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 1200,
      depthMm: 900,
      heightMm: 2100,
    ),
    ObjectCatalogItem(
      id: 'radiator-600',
      name: 'Радиатор 600',
      group: 'Отопление',
      type: PlanObjectType.radiator,
      widthMm: 600,
      depthMm: 120,
      heightMm: 600,
      elevationMm: 120,
    ),
    ObjectCatalogItem(
      id: 'ac-indoor',
      name: 'Кондиционер, внутренний блок',
      group: 'Климат',
      type: PlanObjectType.furniture,
      widthMm: 900,
      depthMm: 220,
      heightMm: 300,
      elevationMm: 2100,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'column-400',
      name: 'Колонна 400×400',
      group: 'Строительные элементы',
      type: PlanObjectType.column,
      widthMm: 400,
      depthMm: 400,
      heightMm: 2700,
    ),
    ObjectCatalogItem(
      id: 'beam-2000',
      name: 'Балка 2000×250×350',
      group: 'Строительные элементы',
      type: PlanObjectType.beam,
      widthMm: 2000,
      depthMm: 250,
      heightMm: 350,
      elevationMm: 2350,
    ),
    ObjectCatalogItem(
      id: 'duct-box-600',
      name: 'Инженерный короб 600×400',
      group: 'Строительные элементы',
      type: PlanObjectType.box,
      widthMm: 600,
      depthMm: 400,
      heightMm: 2700,
    ),
    ObjectCatalogItem(
      id: 'boiler',
      name: 'Бойлер',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 500,
      depthMm: 500,
      heightMm: 900,
      elevationMm: 1500,
    ),
    ObjectCatalogItem(
      id: 'ottoman',
      name: 'Пуф',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 600,
      depthMm: 600,
      heightMm: 450,
    ),
    ObjectCatalogItem(
      id: 'coffee-table',
      name: 'Журнальный стол',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1000,
      depthMm: 600,
      heightMm: 420,
    ),
    ObjectCatalogItem(
      id: 'dresser-1200',
      name: 'Комод 1200',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 1200,
      depthMm: 450,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'nightstand',
      name: 'Прикроватная тумба',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 500,
      depthMm: 450,
      heightMm: 550,
    ),
    ObjectCatalogItem(
      id: 'tv-console-1600',
      name: 'ТВ-тумба 1600',
      group: 'Видео и ТВ',
      type: PlanObjectType.furniture,
      widthMm: 1600,
      depthMm: 400,
      heightMm: 500,
    ),
    ObjectCatalogItem(
      id: 'office-chair',
      name: 'Офисное кресло',
      group: 'Офис',
      type: PlanObjectType.furniture,
      widthMm: 650,
      depthMm: 650,
      heightMm: 1150,
    ),
    ObjectCatalogItem(
      id: 'office-desk-1400',
      name: 'Офисный стол 1400',
      group: 'Офис',
      type: PlanObjectType.furniture,
      widthMm: 1400,
      depthMm: 700,
      heightMm: 750,
    ),
    ObjectCatalogItem(
      id: 'bookcase-1200',
      name: 'Книжный стеллаж 1200',
      group: 'Офис',
      type: PlanObjectType.furniture,
      widthMm: 1200,
      depthMm: 350,
      heightMm: 2000,
    ),
    ObjectCatalogItem(
      id: 'plant-large',
      name: 'Напольное растение',
      group: 'Декор',
      type: PlanObjectType.furniture,
      widthMm: 700,
      depthMm: 700,
      heightMm: 1500,
    ),
    ObjectCatalogItem(
      id: 'towel-warmer-600',
      name: 'Полотенцесушитель 600',
      group: 'Сантехника',
      type: PlanObjectType.radiator,
      widthMm: 600,
      depthMm: 120,
      heightMm: 900,
      elevationMm: 900,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'chandelier-ring',
      name: 'Люстра-кольцо',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 900,
      depthMm: 900,
      heightMm: 350,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'chandelier-branch',
      name: 'Люстра ветви',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 1100,
      depthMm: 700,
      heightMm: 420,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'pendant-single',
      name: 'Подвес одиночный',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 320,
      depthMm: 320,
      heightMm: 650,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'pendant-triple',
      name: 'Подвес тройной',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 900,
      depthMm: 300,
      heightMm: 760,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'ceiling-dome',
      name: 'Потолочный светильник',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 520,
      depthMm: 520,
      heightMm: 130,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'track-3',
      name: 'Трек 3 спота',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 1100,
      depthMm: 140,
      heightMm: 220,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'wall-sconce-updown',
      name: 'Бра вверх/вниз',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 180,
      depthMm: 150,
      heightMm: 300,
      elevationMm: 1650,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'wall-sconce-globe',
      name: 'Бра шар',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 240,
      depthMm: 260,
      heightMm: 280,
      elevationMm: 1600,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'wall-sconce-linear',
      name: 'Бра линейное',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 520,
      depthMm: 120,
      heightMm: 90,
      elevationMm: 1750,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'floor-lamp-arc',
      name: 'Торшер дуговой',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 900,
      depthMm: 500,
      heightMm: 1900,
    ),
    ObjectCatalogItem(
      id: 'sofa-modular',
      name: 'Диван модульный 2800',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 2800,
      depthMm: 1000,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'lounge-chair',
      name: 'Кресло lounge',
      group: 'Мягкая мебель',
      type: PlanObjectType.furniture,
      widthMm: 780,
      depthMm: 850,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'dining-chair-upholstered',
      name: 'Стул мягкий',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 500,
      depthMm: 560,
      heightMm: 880,
    ),
    ObjectCatalogItem(
      id: 'dining-table-1800',
      name: 'Обеденный стол 1800',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 1800,
      depthMm: 900,
      heightMm: 760,
    ),
    ObjectCatalogItem(
      id: 'bar-stool',
      name: 'Барный стул',
      group: 'Столы и стулья',
      type: PlanObjectType.furniture,
      widthMm: 450,
      depthMm: 450,
      heightMm: 980,
    ),
    ObjectCatalogItem(
      id: 'wardrobe-sliding-2000',
      name: 'Шкаф-купе 2000',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 2000,
      depthMm: 650,
      heightMm: 2400,
    ),
    ObjectCatalogItem(
      id: 'chest-tall',
      name: 'Высокий комод',
      group: 'Хранение',
      type: PlanObjectType.furniture,
      widthMm: 800,
      depthMm: 450,
      heightMm: 1200,
    ),
    ObjectCatalogItem(
      id: 'kitchen-island-1800',
      name: 'Кухонный остров 1800',
      group: 'Кухня',
      type: PlanObjectType.furniture,
      widthMm: 1800,
      depthMm: 900,
      heightMm: 920,
    ),
    ObjectCatalogItem(
      id: 'basin-round',
      name: 'Тумба с круглой раковиной',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 620,
      depthMm: 520,
      heightMm: 850,
    ),
    ObjectCatalogItem(
      id: 'shower-glass-1000',
      name: 'Душевая стекло 1000',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 1000,
      depthMm: 1000,
      heightMm: 2100,
    ),
    ObjectCatalogItem(
      id: 'bathtub-freestanding',
      name: 'Ванна отдельностоящая',
      group: 'Сантехника',
      type: PlanObjectType.sanitary,
      widthMm: 1700,
      depthMm: 800,
      heightMm: 600,
    ),
    ObjectCatalogItem(
      id: 'ceiling-linear',
      name: 'Потолочный линейный',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 1200,
      depthMm: 120,
      heightMm: 80,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'chandelier-orbit',
      name: 'Люстра Orbit',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 800,
      depthMm: 800,
      heightMm: 350,
      mount: CatalogMount.ceiling,
    ),
    ObjectCatalogItem(
      id: 'wall-sconce-cylinder',
      name: 'Бра цилиндр',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 160,
      depthMm: 180,
      heightMm: 300,
      elevationMm: 1650,
      mount: CatalogMount.wall,
    ),
    ObjectCatalogItem(
      id: 'floor-lamp-tripod',
      name: 'Торшер тренога',
      group: 'Освещение',
      type: PlanObjectType.lighting,
      widthMm: 600,
      depthMm: 600,
      heightMm: 1700,
    ),
    ObjectCatalogItem(
      id: 'plant-medium',
      name: 'Растение среднее',
      group: 'Декор',
      type: PlanObjectType.furniture,
      widthMm: 500,
      depthMm: 500,
      heightMm: 1000,
    ),
    ObjectCatalogItem(
      id: 'rug-2000x1400',
      name: 'Ковёр 2000×1400',
      group: 'Декор',
      type: PlanObjectType.furniture,
      widthMm: 2000,
      depthMm: 1400,
      heightMm: 35,
    ),
  ];

  static ObjectCatalogItem byId(String id) =>
      items.firstWhere((e) => e.id == id, orElse: () => items.first);

  static List<String> get groups =>
      items.map((e) => e.group).toSet().toList(growable: false)..sort();
  static List<ObjectCatalogItem> inGroup(String group) =>
      items.where((e) => e.group == group).toList(growable: false);
}
